/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algoritmi_hyena_HyenaH */

#ifndef _Included_algoritmi_hyena_HyenaH
#define _Included_algoritmi_hyena_HyenaH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algoritmi_hyena_HyenaH
 * Method:    encrypt
 * Signature: ([BJ[BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algoritmi_hyena_HyenaH_encrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

/*
 * Class:     algoritmi_hyena_HyenaH
 * Method:    decrypt
 * Signature: ([BJ[BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algoritmi_hyena_HyenaH_decrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
