/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algoritmi_locus_lotus_LotusH */

#ifndef _Included_algoritmi_locus_lotus_LotusH
#define _Included_algoritmi_locus_lotus_LotusH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algoritmi_locus_lotus_LotusH
 * Method:    encrypt
 * Signature: ([BJ[BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algoritmi_locus_1lotus_LotusH_encrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

/*
 * Class:     algoritmi_locus_lotus_LotusH
 * Method:    decrypt
 * Signature: ([BJ[BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algoritmi_locus_1lotus_LotusH_decrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
