/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algoritmi_gift_GiftH */

#ifndef _Included_algoritmi_gift_GiftH
#define _Included_algoritmi_gift_GiftH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algoritmi_gift_GiftH
 * Method:    encrypt
 * Signature: ([BJ[BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algoritmi_gift_GiftH_encrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

/*
 * Class:     algoritmi_gift_GiftH
 * Method:    decrypt
 * Signature: ([BJ[BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algoritmi_gift_GiftH_decrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
