/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algoritmi_grain_GrainH */

#ifndef _Included_algoritmi_grain_GrainH
#define _Included_algoritmi_grain_GrainH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algoritmi_grain_GrainH
 * Method:    encrypt
 * Signature: ([BJ[BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algoritmi_grain_GrainH_encrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

/*
 * Class:     algoritmi_grain_GrainH
 * Method:    decrypt
 * Signature: ([BJ[BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algoritmi_grain_GrainH_decrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
