/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algoritmi_xoodyak_XoodyakH */

#ifndef _Included_algoritmi_xoodyak_XoodyakH
#define _Included_algoritmi_xoodyak_XoodyakH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algoritmi_xoodyak_XoodyakH
 * Method:    encrypt
 * Signature: ([BJ[BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algoritmi_xoodyak_XoodyakH_encrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

/*
 * Class:     algoritmi_xoodyak_XoodyakH
 * Method:    decrypt
 * Signature: ([BJ[BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_algoritmi_xoodyak_XoodyakH_decrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
